# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  # Anki: New Basic Note
  - trigger: ":note"
    replace: "START\nBasic\nFront:\nBack:\nTags: #AnkiTag\nEND"

  # Anki: New Cloze Note
  - trigger: ":clz"
    replace: "START\nCloze\n\nTags: #AnkiTag\nEND"

  # Obsidian Fast Stand-up
  - trigger: ":fst"
    replace: "# Fast Project Stand-up {{mydate}}\nAttendees: Paul, Peter, Jordan, John, Kyle, Tomas\n\n\n\n#FAST #DataScience #AI #DataSteward #StandUp #Sync\n\nSee also: \n\n## Prompts"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Obsidian VRA-MQ Stand-up
  - trigger: ":vramq"
    replace: "# VRA-MQ Project Stand-up {{mydate}}\nAttendees: Lisa, Mikayla, Nick, Tori, Camila, Dave, Tom\n\n\n\n#VRAMQ #StandUp #Sync\n\nSee also: \n\n## Prompts"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Obsidian Scale and Standards Stand-up
  - trigger: ":scale"
    replace: "# Scale & Standards Weekly Sync {{mydate}}\nAttendees: Mark, Joey, Meha, Kaytlin, Adam, Tim, Chris, Eric\n\n\n\n#AICC #AI #StandUp #Sync #ScaleStandards\nSee also: \n\n## Prompts"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Obsidian PS2 Stand-Up
  - trigger: ":ps2"
    replace: "# PS2 Weekly Stand-Up {{mydate}}\nAttendees: Yongcaho, Monica, Jian, Parth, Bea, Matt\n\n\n\n#PS2 #DataSteward #StandUp\n\nSee also: \n\n## Prompts"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

