# espanso match file

matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # Anki: New Cloze Note
  - trigger: ":clz"
    replace: "START\nCloze\n\nTags: #AnkiTag\nEND"

  - trigger: ":due"
    replace: "📅 {{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Insert scheduled date
  - trigger: ":sch"
    replace: "⏳ {{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d" 

  # Insert completion date
  - trigger: ":comp"
    replace: "✅ {{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Hi priority
  - trigger: ";;high"
    replace: "⏫"

  # Med priority
  - trigger: ";;med"
    replace: "🔼"

  # Low priority
  - trigger: ";;low"
    replace: "🔽"

  # Green
  - trigger: ";;g"
    replace: "🟩"
  # Yellow
  - trigger: ";;y"
    replace: "🟨"
  # Red
  - trigger: ";;r"
    replace: "🟥"

# Project Autocompletes
  # Project Personal
  - trigger: ";;pp"
    replace: "[Project::Personal]"
  - trigger: ";;pcom"
    replace: "[Project::Community]"
  - trigger: ";;pcon"
    replace: "[Project::Constitution]"
  - trigger: ";;pcraft"
    replace: "[Project::Craft]"
  - trigger: ";;pcont"
    replace: "[Project::Contemplation]"
  - trigger: ";;pcds"
    replace: "[Project::CDS]"
  - trigger: ";;pmeas"
    replace: "[Project::Measure]"
  - trigger: ";;pdss"
    replace: "[Project::DSS4AS]"

  # Insert food diary template
  - trigger: ";;food"
    replace: "## {{mydate}}\n\n### Breakfast\n\n- Athletic Greens\n- Coffee\n- Oatmeal with flax seed meal and raw honey\n- Fruit (strawberries, blueberries, blackberries, grapes)\n\n\n### Lunch\n\n### Snack\n\n### Dinner\n\n### Supplements & Meds\n\n- 1000 mg krill oil\n- Two drops of Vitamin D\n- 20 mg Rosuvastatin\n- 300 mg CoQ10\n- 400 mg Magnesium"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

